---

version: 2
jobs:

  gomplate_tests:
    docker:
    - image: hairyhenderson/gomplate:v3.2.0-alpine
    resource_class: medium
    working_directory: ~/scale-network/tests/unit/openwrt
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: install diffutils
        command: apk update && apk add diffutils

    # Netgear WNDR 3700v2, 3800, 3800ch configs
    - run:
        name: openwrt ar71xx golden file test
        command: sh -x test.sh -t ar71xx

    # TP-Link c2600 configs
    - run:
        name: openwrt ipq806x golden file test
        command: sh -x test.sh -t ipq806x

  # TODO: Figure out when to do end-to-end build test
  # builds take a long time and should be done
  # outside of initial ci testing
  openwrt_nightly_build:
    docker:
    - image: sarcasticadmin/openwrt-buildroot
      resource_class: medium
      working_directory: ~/scale-network/openwrt
      steps:
    - checkout:
      path: ~/scale-network

    - run:
        name: build openwrt image
        command: TARGET=ar71xx make templates build-img

    - run:
        name: build openwrt image
        command: TARGET=ipq806x make templates build-img

    - run:
        command: |
            mkdir -p /tmp/ar71xx
	    cp /home/openwrt/workspace/scale-network/openwrt/build/source-ar71xx-*/bin/targets/ar71xx/generic/openwrt-ar71xx-generic-*factory.img /tmp/ar71xx
	    cp /home/openwrt/workspace/scale-network/openwrt/build/source-ar71xx-*/bin/targets/ar71xx/generic/sha256sums /tmp/ar71xx
	    cp /home/openwrt/workspace/scale-network/openwrt/build/source-ar71xx-*/bin/targets/ar71xx/generic/6sums /tmp/ar71xx

    - run:
        command: |
            mkdir -p /tmp/ipq806x
	    cp /home/openwrt/workspace/scale-network/openwrt/build/source-ipq806x-*/bin/targets/ipq806x/generic/openwrt-ipq806x-generic-*factory.img /tmp/ipq806x
	    cp /home/openwrt/workspace/scale-network/openwrt/build/source-ipq806x-*/bin/targets/ipq806x/generic/sha256sums /tmp/ipq806x
	    cp /home/openwrt/workspace/scale-network/openwrt/build/source-ipq806x-*/bin/targets/ipq806x/generic/6sums /tmp/ipq806x
    - store_artifacts:
        path: /tmp/ar71xx
    - store_artifacts:
        path: /tmp/ipq806x

  ansible_lint:
    docker:
    - image: circleci/python:3.7.2-node-browsers-legacy
    resource_class: medium
    working_directory: ~/scale-network/ansible
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: install ansible-lint
        command: sudo pip install ansible-lint

    - run:
        name: lint scale.yml
        command: ansible-lint -x 503 -x 405 etc/ansible/scale.yml

    - run:
        name: install pylint
        command: sudo pip install pylint

    - run:
        name: lint inventory.py
        command: pylint inventory.py --confidence=HIGH

    - run:
        name: test inventory.py
        command: ./inventory.py | jq

workflows:
  version: 2
  build_all:
    jobs:
    - gomplate_tests
    - ansible_lint
